video:
#  name: "2017-09-14 21.53.59.mp4"
  name: "IMG_3664.MOV"
  sizeChange:
    min: 30
    step: 5
    max: 35 #no es inclusivo
  positionChange: ["NW","N","NE","W","C","E","SW","S","SE"]
heartbeats: 64
duration: 60 #en porcentaje


