video:
  name: "2017-09-14 21.53.59.mp4"
  sizeChange:
    min: 20
    step: 5
    max: 25 #no es inclusivo
  positionChange: ["NW","N","NE","W","C","E","SW","S","SE"]
heartbeats: 60
duration: 1 #en porcentaje
